% getInterpPad.m
%
% Function that returns padding at the beginning or end of a vector.
% Padding is generated by cubic spline interpolation
%
% INPUTS:
%   vec - vector to pad
%   padLen - length of padding, in samples
%   padSide - which side to pad, 'start' or 'end'
%
% OUTPUTS:
%   pad - vector for calculated padding
%
% CREATED: 8/30/21 - HHY
%
% UPDATED:
%   8/31/21 - HHY - fixed bug with values going outside of data range with
%       interpolation and resampling
%
function pad = getInterpPad(vec, padLen, padSide)

    % indicies for vector, use as x-values for interpolation
    ind = 1:length(vec);
    
    if strcmpi(padSide, 'start')
        % x-values for interpolation (before vector start)
        interpXvals = fliplr(0:-1:((padLen - 1) * -1));
    elseif strcmpi(padSide, 'end')
        interpXvals = (length(vec) + 1):(length(vec) + padLen);
    else
        disp('padSide must be start or end')
        return;
    end
    
    % get padding
    pad = interp1(ind, vec, interpXvals, 'linear', 'extrap');
    
    % pad is always row vector; if original vector is column vector, make
    %  pad column vector
    if iscolumn(vec)
        pad = pad';
    end
end